/**
 * review-log-update.ts
 *
 * review-log-update.sh の TypeScript 移植。
 * review-log.yaml にイテレーションブロックを追記する。
 *
 * 主な変更点:
 * - bash サブプロセス → 型付き関数呼び出し
 * - sed -i → TypeScript ファイル操作
 * - cat >> → FileSystem 経由の追記
 *
 * review-log-update.sh 全体参照。
 */

import path from "node:path";

import type { FileSystem } from "./interfaces.js";

export interface LogUpdateOptions {
  logPath: string;
  issuesFile?: string;
  verdicts: string;
  iteration: number;
  fixedIds?: string;
  fileSystem: FileSystem;
}

/**
 * review-log.yaml にイテレーションブロックを追記する。
 * review-log-update.sh のメインロジック全体に対応。
 *
 * @returns logPath（元の sh 版との互換性）
 */
export function updateReviewLog(opts: LogUpdateOptions): string {
  const { logPath, issuesFile, verdicts, iteration, fixedIds, fileSystem } = opts;

  const now = new Date().toISOString().replace(/\.\d+Z$/, "Z");

  // ログファイルが存在しない場合は初期化
  if (!fileSystem.exists(logPath)) {
    const logDir = path.dirname(logPath);
    // ディレクトリは writeFile が自動作成するが、念のため確認
    const header = [
      "# Review Log",
      "# Auto-generated by review-runner",
      `created: ${now}`,
      "iterations:",
      "",
    ].join("\n");
    fileSystem.writeFile(logPath, header);
  } else {
    // レガシーログの "iterations: []" を "iterations:" に修正
    const existing = fileSystem.readFile(logPath);
    if (existing.includes("iterations: []")) {
      fileSystem.writeFile(logPath, existing.replace(/^iterations: \[\]$/m, "iterations:"));
    }
  }

  // issues ファイルを読み込む
  let issueLines: string[] = [];
  if (issuesFile && fileSystem.exists(issuesFile)) {
    try {
      const issueContent = fileSystem.readFile(issuesFile);
      issueLines = issueContent.split("\n").filter(Boolean);
    } catch { /* no-op */ }
  }

  // イテレーションブロックを構築
  const block: string[] = [];
  block.push("");
  block.push(`  - iteration: ${iteration}`);
  block.push(`    timestamp: ${now}`);
  block.push(`    verdicts: "${verdicts}"`);

  if (issueLines.length > 0) {
    block.push("    issues:");
    for (const issueLine of issueLines) {
      const parts = issueLine.split("|");
      const id = parts[0] ?? "";
      const severity = parts[1] ?? "";
      const description = parts[2] ?? "";
      const location = parts[3] ?? "";
      const persona = parts[4] ?? "";
      block.push(`      - id: ${id}`);
      block.push(`        severity: ${severity}`);
      block.push(`        description: "${description}"`);
      block.push(`        location: "${location}"`);
      block.push(`        persona: ${persona}`);
    }
  } else {
    block.push("    issues: []");
  }

  // 前イテレーションの修正済み IDs
  if (fixedIds) {
    const fixedArray = fixedIds
      .split(",")
      .map((id) => id.trim())
      .filter(Boolean);
    if (fixedArray.length > 0) {
      block.push("    fixed:");
      for (const fid of fixedArray) {
        block.push(`      - ${fid}`);
      }
    }
  }

  // ログファイルに追記
  const existingContent = fileSystem.readFile(logPath);
  const appendContent = block.join("\n") + "\n";
  fileSystem.writeFile(logPath, existingContent + appendContent);

  return logPath;
}
