#!/usr/bin/env bash
# setup-glm-teammate.sh — Agent Teams の Teammate を GLM-5 (Z.AI API) に差し替えるセットアップ
#
# 使い方:
#   bash scripts/setup-glm-teammate.sh
#
# 前提:
#   - Claude Code (claude) がインストール済み
#   - Z.AI の API キーを所持
#
# 生成物:
#   /usr/local/bin/glm          — GLM-5 ラッパー（sudo 必要）
#   /usr/local/bin/glm-setup    — キー変更時の再生成ヘルパー（sudo 必要）
#   ~/.claude/glm-mcp.json      — Z.AI MCP サーバー設定
#   ~/.bashrc                   — 環境変数追記
#   ~/.claude/settings.json     — env ブロック追記
set -euo pipefail

echo "=== GLM-5 Teammate Setup ==="
echo ""

# ─── 1. 前提チェック ───
missing=()
for cmd in claude envsubst jq node; do
  command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "ERROR: 以下のコマンドが見つかりません: ${missing[*]}" >&2
  exit 1
fi
echo "[OK] 前提チェック完了 (claude, envsubst, jq, node)"

# ─── 2. API キー入力 ───
if [ -n "${ZAI_API_KEY:-}" ]; then
  echo "ZAI_API_KEY が環境変数に設定されています。"
  read -rp "既存のキーを使用しますか？ [Y/n] " use_existing
  if [[ "${use_existing:-Y}" =~ ^[Nn] ]]; then
    read -rsp "Z.AI API キーを入力: " ZAI_API_KEY
    echo ""
  fi
else
  read -rsp "Z.AI API キーを入力: " ZAI_API_KEY
  echo ""
fi

if [ -z "${ZAI_API_KEY:-}" ]; then
  echo "ERROR: API キーが空です" >&2
  exit 1
fi
export ZAI_API_KEY

# ─── 3. /usr/local/bin/glm ラッパー生成（sudo） ───
# API キーは実行時に展開して直接埋め込む（Teammate プロセスは .bashrc を読まないため）
sudo tee /usr/local/bin/glm > /dev/null << WRAPPER
#!/usr/bin/env bash
# Claude Code wrapper for Z.AI (智谱AI GLM) API
# Generated by setup-glm-teammate.sh — キー変更時は glm-setup で再生成
set -euo pipefail

export ANTHROPIC_BASE_URL="https://api.z.ai/api/anthropic"
export ANTHROPIC_AUTH_TOKEN="${ZAI_API_KEY}"
export API_TIMEOUT_MS="3000000"

export ANTHROPIC_DEFAULT_OPUS_MODEL="GLM-5"
export ANTHROPIC_DEFAULT_SONNET_MODEL="GLM-5"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="GLM-5"

exec claude --mcp-config ~/.claude/glm-mcp.json "\$@"
WRAPPER
sudo chmod +x /usr/local/bin/glm
echo "[OK] /usr/local/bin/glm 生成完了（キー埋め込み + MCP）"

# ─── 4. ~/.claude/glm-mcp.json.template 作成 ───
mkdir -p "$HOME/.claude"
cat > "$HOME/.claude/glm-mcp.json.template" << 'TEMPLATE'
{
  "mcpServers": {
    "web-search-prime": {
      "type": "http",
      "url": "https://api.z.ai/api/mcp/web_search_prime/mcp",
      "headers": {
        "Authorization": "Bearer ${ZAI_API_KEY}"
      }
    },
    "web-reader": {
      "type": "http",
      "url": "https://api.z.ai/api/mcp/web_reader/mcp",
      "headers": {
        "Authorization": "Bearer ${ZAI_API_KEY}"
      }
    },
    "zread": {
      "type": "http",
      "url": "https://api.z.ai/api/mcp/zread/mcp",
      "headers": {
        "Authorization": "Bearer ${ZAI_API_KEY}"
      }
    },
    "zai-vision": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@z_ai/mcp-server"],
      "env": {
        "Z_AI_API_KEY": "${ZAI_API_KEY}",
        "Z_AI_MODE": "ZAI"
      }
    }
  }
}
TEMPLATE
echo "[OK] ~/.claude/glm-mcp.json.template 作成完了"

# ─── 5. テンプレートから MCP 設定を展開 ───
envsubst '${ZAI_API_KEY}' < "$HOME/.claude/glm-mcp.json.template" > "$HOME/.claude/glm-mcp.json"
chmod 600 "$HOME/.claude/glm-mcp.json"
echo "[OK] ~/.claude/glm-mcp.json 生成完了 (chmod 600)"

# ─── 6. /usr/local/bin/glm-setup ヘルパー生成（sudo） ───
sudo tee /usr/local/bin/glm-setup > /dev/null << 'SETUP_SCRIPT'
#!/usr/bin/env bash
# glm-setup — API キー変更後に glm ラッパーと MCP 設定を再生成
set -euo pipefail

if [ -z "${ZAI_API_KEY:-}" ]; then
  echo "ERROR: ZAI_API_KEY が設定されていません。" >&2
  echo "  export ZAI_API_KEY='your-key-here'" >&2
  exit 1
fi

# MCP 設定を再生成
TEMPLATE="$HOME/.claude/glm-mcp.json.template"
OUTPUT="$HOME/.claude/glm-mcp.json"
if [ ! -f "$TEMPLATE" ]; then
  echo "ERROR: テンプレートが見つかりません: $TEMPLATE" >&2
  echo "setup-glm-teammate.sh を先に実行してください。" >&2
  exit 1
fi
envsubst '${ZAI_API_KEY}' < "$TEMPLATE" > "$OUTPUT"
chmod 600 "$OUTPUT"
echo "[OK] MCP 設定を再生成: $OUTPUT"
echo "  MCP servers: $(jq -r '.mcpServers | keys[]' "$OUTPUT" 2>/dev/null | tr '\n' ' ')"

# glm ラッパーを再生成（キー埋め込み + MCP）
sudo tee /usr/local/bin/glm > /dev/null << GLM_INNER
#!/usr/bin/env bash
# Claude Code wrapper for Z.AI (智谱AI GLM) API
# Generated by glm-setup — キー変更時は glm-setup で再生成
set -euo pipefail

export ANTHROPIC_BASE_URL="https://api.z.ai/api/anthropic"
export ANTHROPIC_AUTH_TOKEN="${ZAI_API_KEY}"
export API_TIMEOUT_MS="3000000"

export ANTHROPIC_DEFAULT_OPUS_MODEL="GLM-5"
export ANTHROPIC_DEFAULT_SONNET_MODEL="GLM-5"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="GLM-5"

exec claude --mcp-config ~/.claude/glm-mcp.json "\$@"
GLM_INNER
sudo chmod +x /usr/local/bin/glm
echo "[OK] glm ラッパーを再生成（キー埋め込み済み）"
SETUP_SCRIPT
sudo chmod +x /usr/local/bin/glm-setup
echo "[OK] /usr/local/bin/glm-setup 生成完了"

# ─── 7. ~/.bashrc に ZAI_API_KEY + CLAUDE_CODE_TEAMMATE_COMMAND 追記/更新 ───
# settings.json の env だけでは Teammate プロセスに伝播しないケースがあるため、
# .bashrc にもフルパスで設定する（ベルト＆サスペンダー方式）
BASHRC="$HOME/.bashrc"

if grep -q '^export ZAI_API_KEY=' "$BASHRC" 2>/dev/null; then
  sed -i "s|^export ZAI_API_KEY=.*|export ZAI_API_KEY=\"${ZAI_API_KEY}\"|" "$BASHRC"
  echo "[OK] ~/.bashrc の ZAI_API_KEY を更新"
else
  printf '\n# === Z.AI GLM-5 Teammate ===\nexport ZAI_API_KEY="%s"\n' "$ZAI_API_KEY" >> "$BASHRC"
  echo "[OK] ~/.bashrc に ZAI_API_KEY を追加"
fi

if grep -q '^export CLAUDE_CODE_TEAMMATE_COMMAND=' "$BASHRC" 2>/dev/null; then
  sed -i 's|^export CLAUDE_CODE_TEAMMATE_COMMAND=.*|export CLAUDE_CODE_TEAMMATE_COMMAND="/usr/local/bin/glm"|' "$BASHRC"
  echo "[OK] ~/.bashrc の CLAUDE_CODE_TEAMMATE_COMMAND を更新"
else
  printf 'export CLAUDE_CODE_TEAMMATE_COMMAND="/usr/local/bin/glm"\n' >> "$BASHRC"
  echo "[OK] ~/.bashrc に CLAUDE_CODE_TEAMMATE_COMMAND を追加"
fi

# ─── 8. ~/.claude/settings.json に env 追加 ───
SETTINGS="$HOME/.claude/settings.json"
if [ -f "$SETTINGS" ]; then
  # CLAUDE_CODE_TEAMMATE_COMMAND を追加/更新
  jq '.env.CLAUDE_CODE_TEAMMATE_COMMAND = "/usr/local/bin/glm"' "$SETTINGS" > /tmp/settings.json.tmp
  mv /tmp/settings.json.tmp "$SETTINGS"
  echo "[OK] settings.json に CLAUDE_CODE_TEAMMATE_COMMAND を設定"
else
  echo "[WARN] ~/.claude/settings.json が存在しないためスキップ"
fi

# ─── 9. 検証 ───
echo ""
echo "=== 検証 ==="
echo "glm:        $(which glm 2>/dev/null || echo 'NOT FOUND')"
echo "glm-setup:  $(which glm-setup 2>/dev/null || echo 'NOT FOUND')"
echo "MCP JSON:   $(jq -e . "$HOME/.claude/glm-mcp.json" >/dev/null 2>&1 && echo 'valid' || echo 'INVALID')"
if [ -f "$SETTINGS" ]; then
  echo "settings:   $(jq -e . "$SETTINGS" >/dev/null 2>&1 && echo 'valid' || echo 'INVALID')"
  echo "teammate:   $(jq -r '.env.CLAUDE_CODE_TEAMMATE_COMMAND // "NOT SET"' "$SETTINGS" 2>/dev/null)"
fi
echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "使い方:"
echo "  glm              # GLM-5 で Claude Code を起動"
echo "  glm -p 'prompt'  # GLM-5 でワンショット実行"
echo "  claude            # 通常の Claude (Anthropic API)"
echo "                    # → Team 起動時、Teammate だけ GLM-5"
echo "  glm-setup         # キー変更後に MCP 設定と glm を再生成"
echo ""
echo "注意: 新しいターミナルを開くか、source ~/.bashrc を実行してください。"
